
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-menu-item-review-e2e-tests","number":124,"title":"Il menu item review e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/124"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-menu-item-review-integration-tests","number":120,"title":"Il menu item review integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/120"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-recreq-test","number":118,"title":"Integration test for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/118"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-table","number":95,"title":"pc-table-component-helprequests","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/95"}]
