
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDOCNntvg","is_bot":false,"login":"kwilliams812","name":"Kade Williams"},"headRefName":"Kade-CopyBackendForOrganization","number":63,"title":"Kade - Copied CRUD backend organization files from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/63"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-fixture","number":62,"title":"Added articlesFixtures.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/62"}]
