
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-form-component","number":68,"title":"Add Articles form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/68"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-fixtures","number":67,"title":"Pc add fixtures for helprequest table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/67"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-commit-fixtures","number":66,"title":"il- add javascript fixtures for MenuItemReview table","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/66"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-copy-files-from-backend","number":65,"title":"copied backend files for CRUD operations to team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/65"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-copy-backend-for-menu-item-review","number":64,"title":"il - copy backend CRUD operations from team01 for the commits table","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/64"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-fixture","number":62,"title":"Added articlesFixtures.js","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/62"}]
