
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-index-page","number":132,"title":"Pc helprequest index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/132"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-EDITpage","number":131,"title":"Pc helprequest edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/131"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-createpage","number":128,"title":"Pc helprequest createpage","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/128"}]
