
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-recreq-form","number":75,"title":"Dz recreq form","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/75"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-placeholder","number":74,"title":"Create placeholder pages for Edit/Create/Index for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/74"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"RecReq","number":73,"title":"Form Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/73"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-table-component","number":71,"title":"Create Articles table component","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/71"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-form-component","number":68,"title":"Add Articles form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/68"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-fixtures","number":67,"title":"Pc add fixtures for helprequest table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/67"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-commit-fixtures","number":66,"title":"il- add javascript fixtures for MenuItemReview table","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/66"}]
