
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-menu-item-review-form","number":92,"title":"Il - add form for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/92"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-recreq-new-index","number":91,"title":"Dz recreq new index","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/91"},{"author":{"id":"U_kgDOB2-VXA","is_bot":false,"login":"daisyzhongg","name":""},"headRefName":"dz-recreq-create-page","number":88,"title":"Create Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/88"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-form-component-for-help-request","number":87,"title":"Pc form component for help request","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/87"},{"author":{"id":"MDQ6VXNlcjY1OTQ0NzE3","is_bot":false,"login":"klai890","name":"Karena Lai"},"headRefName":"karena-articles-edit-page","number":86,"title":"Karena articles edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/86"},{"author":{"id":"U_kgDOCVHShQ","is_bot":false,"login":"xanxp","name":"Xin Ping Xandra Wong"},"headRefName":"xw-UCSBDiningCommonsMenuItems-edit-page","number":83,"title":"xw - ucsb dining commons menu items edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/83"},{"author":{"id":"U_kgDOCVHShQ","is_bot":false,"login":"xanxp","name":"Xin Ping Xandra Wong"},"headRefName":"xw-UCSBDiningCommonsMenuItems-index-page","number":82,"title":"xw - ucsb dining commons menu items index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/82"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-fixtures","number":67,"title":"Pc add fixtures for helprequest table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/67"},{"author":{"id":"U_kgDODDnxkQ","is_bot":false,"login":"ilandry-ucsb","name":""},"headRefName":"il-commit-fixtures","number":66,"title":"il- add javascript fixtures for MenuItemReview table","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/66"}]
