
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-03
owner: ucsb-cs156-s25
repo_name: team02-s25-03
pull_requests: [{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"revert-97-pc-helprequest-placeholders","number":106,"title":"Revert \"pc- added placeholder pages for helprequest create, edit, and index\"","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/106"},{"author":{"id":"U_kgDOCNntvg","is_bot":false,"login":"kwilliams812","name":"Kade Williams"},"headRefName":"Kade-UCSBOrganizationIndexPage","number":104,"title":"Kade - Index Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/104"},{"author":{"id":"U_kgDOBvSp8w","is_bot":false,"login":"saahasburicha","name":"Saahas Buricha"},"headRefName":"pc-helprequest-table","number":95,"title":"pc-table-component-helprequests","url":"https://github.com/ucsb-cs156-s25/team02-s25-03/pull/95"}]
